<?php
/**
 * Created by PhpStorm.
 * User: PGARZARO
 * Date: 13/01/2018
 * Time: 20:08
 */

namespace AppBundle\Repository;


/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository{

}